https://docs.scipy.org/doc/scipy/reference/stats.html

https://www.statsmodels.org/stable/index.html

a tutorial for some tests in machine learning:

https://machinelearningmastery.com/statistical-hypothesis-tests-in-python-cheat-sheet/

Plotting on Meshes to Understand why it works

In [3]:
import numpy as np
xx,yy=np.meshgrid([1,2,3,4],[.1,.2,.3,.4])

In [4]:
xx

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [5]:
yy

array([[0.1, 0.1, 0.1, 0.1],
       [0.2, 0.2, 0.2, 0.2],
       [0.3, 0.3, 0.3, 0.3],
       [0.4, 0.4, 0.4, 0.4]])

In [6]:
np.ravel(xx)

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

In [7]:
np.ravel(yy)

array([0.1, 0.1, 0.1, 0.1, 0.2, 0.2, 0.2, 0.2, 0.3, 0.3, 0.3, 0.3, 0.4,
       0.4, 0.4, 0.4])

In [8]:
np.c_[np.ravel(xx),np.ravel(yy)]

array([[1. , 0.1],
       [2. , 0.1],
       [3. , 0.1],
       [4. , 0.1],
       [1. , 0.2],
       [2. , 0.2],
       [3. , 0.2],
       [4. , 0.2],
       [1. , 0.3],
       [2. , 0.3],
       [3. , 0.3],
       [4. , 0.3],
       [1. , 0.4],
       [2. , 0.4],
       [3. , 0.4],
       [4. , 0.4]])

# Neural Networks

In [9]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [10]:
import warnings
warnings.simplefilter(action="ignore",category="FutureWarning")

In [14]:
import pandas as pd

ImportError: C extension: 'iNaT' not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.