In [124]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [125]:
file_dir = "data/House/"

In [126]:
df = pd.read_csv(file_dir+'train.csv')

In [127]:
dfTemp = pd.read_csv(file_dir+'train.csv')

In [128]:
pd.set_option('display.max_columns', 500)
df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive

In [129]:
df.drop(['Id','Street','Alley','Utilities','PoolArea','Fence','LotConfig','ScreenPorch','3SsnPorch','Condition1','Condition2','OpenPorchSF','EnclosedPorch','WoodDeckSF','GarageCond','GarageQual','GarageArea','Exterior1st','Exterior2nd','MasVnrType','MasVnrArea','Foundation','BsmtQual','BsmtCond','BsmtExposure','BsmtFinType1','BsmtFinSF1','BsmtFinType2','BsmtFinSF2','BsmtUnfSF','TotalBsmtSF','Heating','HeatingQC','Electrical','1stFlrSF','2ndFlrSF','LowQualFinSF','ExterCond','ExterQual','GrLivArea','BsmtFullBath','BsmtHalfBath','BedroomAbvGr','KitchenAbvGr','Functional','FireplaceQu','GarageYrBlt','GarageFinish','MiscFeature','MiscVal','MSSubClass','LotFrontage','LandSlope','RoofStyle','RoofMatl','PavedDrive','LotShape'], axis=1, inplace=True)

In [130]:
df.columns

Index(['MSZoning', 'LotArea', 'LandContour', 'Neighborhood', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'CentralAir', 'FullBath', 'HalfBath', 'KitchenQual', 'TotRmsAbvGrd',
       'Fireplaces', 'GarageType', 'GarageCars', 'PoolQC', 'MoSold', 'YrSold',
       'SaleType', 'SaleCondition', 'SalePrice'],
      dtype='object')

In [131]:
df.head(1)

MSZoning  LotArea LandContour Neighborhood BldgType HouseStyle  OverallQual  \
0       RL     8450         Lvl      CollgCr     1Fam     2Story            7   

   OverallCond  YearBuilt  YearRemodAdd CentralAir  FullBath  HalfBath  \
0            5       2003          2003          Y         2         1   

  KitchenQual  TotRmsAbvGrd  Fireplaces GarageType  GarageCars PoolQC  MoSold  \
0          Gd             8           0     Attchd           2    NaN       2   

   YrSold SaleType SaleCondition  SalePrice  
0    2008       WD        Normal     208500

In [132]:
#Extract the Test Data
Y = df["SalePrice"].values
Y

array([208500, 181500, 223500, ..., 266500, 142125, 147500])

In [133]:
df.apply(pd.value_counts)

MSZoning  LotArea  LandContour  Neighborhood  BldgType  HouseStyle  \
0             NaN      NaN          NaN           NaN       NaN         NaN   
1             NaN      NaN          NaN           NaN       NaN         NaN   
2             NaN      NaN          NaN           NaN       NaN         NaN   
3             NaN      NaN          NaN           NaN       NaN         NaN   
4             NaN      NaN          NaN           NaN       NaN         NaN   
5             NaN      NaN          NaN           NaN       NaN         NaN   
6             NaN      NaN          NaN           NaN       NaN         NaN   
7             NaN      NaN          NaN           NaN       NaN         NaN   
8             NaN      NaN          NaN           NaN       NaN         NaN   
9             NaN      NaN          NaN           NaN       NaN         NaN   
10            NaN      NaN          NaN           NaN       NaN         NaN   
11            NaN      NaN          NaN           NaN       NaN         NaN   
12            NaN      NaN          NaN           NaN       NaN         NaN   
14            NaN      NaN          NaN           NaN       NaN         NaN   
1300          NaN      1.0          NaN           NaN       NaN         NaN   
1477          NaN      1.0          NaN           NaN       NaN         NaN   
1491          NaN      1.0          NaN           NaN       NaN         NaN   
1526          NaN      1.0          NaN           NaN       NaN         NaN   
1533          NaN      2.0          NaN           NaN       NaN         NaN   
1596          NaN      1.0          NaN           NaN       NaN         NaN   
1680          NaN     10.0          NaN           NaN       NaN         NaN   
1869          NaN      1.0          NaN           NaN       NaN         NaN   
1872          NaN      NaN          NaN           NaN       NaN         NaN   
1875          NaN      NaN          NaN           NaN       NaN         NaN   
1880          NaN      NaN          NaN           NaN       NaN         NaN   
1882          NaN      NaN          NaN           NaN       NaN         NaN   
1885          NaN      NaN          NaN           NaN       NaN         NaN   
1890          NaN      2.0          NaN           NaN       NaN         NaN   
1892          NaN      NaN          NaN           NaN       NaN         NaN   
1893          NaN      NaN          NaN           NaN       NaN         NaN   
...           ...      ...          ...           ...       ...         ...   
MeadowV       NaN      NaN          NaN          17.0       NaN         NaN   
Mitchel       NaN      NaN          NaN          49.0       NaN         NaN   
N             NaN      NaN          NaN           NaN       NaN         NaN   
NAmes         NaN      NaN          NaN         225.0       NaN         NaN   
NPkVill       NaN      NaN          NaN           9.0       NaN         NaN   
NWAmes        NaN      NaN          NaN          73.0       NaN         NaN   
New           NaN      NaN          NaN           NaN       NaN         NaN   
NoRidge       NaN      NaN          NaN          41.0       NaN         NaN   
Normal        NaN      NaN          NaN           NaN       NaN         NaN   
NridgHt       NaN      NaN          NaN          77.0       NaN         NaN   
OldTown       NaN      NaN          NaN         113.0       NaN         NaN   
Oth           NaN      NaN          NaN           NaN       NaN         NaN   
Partial       NaN      NaN          NaN           NaN       NaN         NaN   
RH           16.0      NaN          NaN           NaN       NaN         NaN   
RL         1151.0      NaN          NaN           NaN       NaN         NaN   
RM          218.0      NaN          NaN           NaN       NaN         NaN   
SFoyer        NaN      NaN          NaN           NaN       NaN        37.0   
SLvl          NaN      NaN          NaN           NaN       NaN        65.0   
SWISU         NaN      NaN          NaN          25.0      

In [134]:
df.loc[dfTemp['YrSold'] > 2000]

MSZoning  LotArea LandContour Neighborhood BldgType HouseStyle  \
0          RL     8450         Lvl      CollgCr     1Fam     2Story   
1          RL     9600         Lvl      Veenker     1Fam     1Story   
2          RL    11250         Lvl      CollgCr     1Fam     2Story   
3          RL     9550         Lvl      Crawfor     1Fam     2Story   
4          RL    14260         Lvl      NoRidge     1Fam     2Story   
5          RL    14115         Lvl      Mitchel     1Fam     1.5Fin   
6          RL    10084         Lvl      Somerst     1Fam     1Story   
7          RL    10382         Lvl       NWAmes     1Fam     2Story   
8          RM     6120         Lvl      OldTown     1Fam     1.5Fin   
9          RL     7420         Lvl      BrkSide   2fmCon     1.5Unf   
10         RL    11200         Lvl       Sawyer     1Fam     1Story   
11         RL    11924         Lvl      NridgHt     1Fam     2Story   
12         RL    12968         Lvl       Sawyer     1Fam     1Story   
13         RL    10652         Lvl      CollgCr     1Fam     1Story   
14         RL    10920         Lvl        NAmes     1Fam     1Story   
15         RM     6120         Lvl      BrkSide     1Fam     1.5Unf   
16         RL    11241         Lvl        NAmes     1Fam     1Story   
17         RL    10791         Lvl       Sawyer   Duplex     1Story   
18         RL    13695         Lvl      SawyerW     1Fam     1Story   
19         RL     7560         Lvl        NAmes     1Fam     1Story   
20         RL    14215         Lvl      NridgHt     1Fam     2Story   
21         RM     7449         Bnk       IDOTRR     1Fam     1.5Unf   
22         RL     9742         Lvl      CollgCr     1Fam     1Story   
23         RM     4224         Lvl      MeadowV   TwnhsE     1Story   
24         RL     8246         Lvl       Sawyer     1Fam     1Story   
25         RL    14230         Lvl      NridgHt     1Fam     1Story   
26         RL     7200         Lvl        NAmes     1Fam     1Story   
27         RL    11478         Lvl      NridgHt     1Fam     1Story   
28         RL    16321         Lvl        NAmes     1Fam     1Story   
29         RM     6324         Lvl      BrkSide     1Fam     1Story   
...       ...      ...         ...          ...      ...        ...   
1430       RL    21930         Lvl      Gilbert     1Fam     2Story   
1431       RL     4928         Lvl      NPkVill   TwnhsE     1Story   
1432       RL    10800         Lvl      OldTown     1Fam     1Story   
1433       RL    10261         Lvl      Gilbert     1Fam     2Story   
1434       RL    17400         Low      Mitchel     1Fam     1Story   
1435       RL     8400         Lvl        NAmes     1Fam     1Story   
1436       RL     9000         Lvl        NAmes     1Fam     1Story   
1437       RL    12444         Lvl      NridgHt     1Fam     1Story   
1438       RM     7407         Lvl      OldTown     1Fam     1Story   
1439       RL    11584         Lvl       NWAmes     1Fam       SLvl   
1440       RL    11526         Bnk      Crawfor     1Fam     2.5Fin   
1441       RM     4426         Lvl      CollgCr   TwnhsE     1Story   
1442       FV    11003         Lvl      Somerst     1Fam     2Story   
1443       RL     8854         Lvl      BrkSide     1Fam     1.5Unf   
1444       RL     8500         Lvl      CollgCr     1Fam     1Story   
1445       RL     8400         Lvl       Sawyer     1Fam     SFoyer   
1446       RL    26142         Lvl      Mitchel     1Fam     1Story   
1447       RL    10000         Lvl      CollgCr     1Fam     2Story   
1448       RL    11767         Lvl      Edwards     1Fam     2Story   
1449       RM     1533         Lvl      MeadowV    Twnhs     SFoyer   
1450       RL     9000         Lvl        NAmes   Duplex     2Story   
1451       RL     9262         Lvl      Somerst     1Fam     1Story   
1452       RM     3675         Lvl      Edwards   TwnhsE       SLvl   
1453       RL    17217         Lvl      Mitchel     1Fam     1Story   
1454       FV     7500       

In [135]:
X1=np.array(df[["OverallQual","SalePrice"]])
X1[:5]

array([[     7, 208500],
       [     6, 181500],
       [     7, 223500],
       [     7, 140000],
       [     8, 250000]])

In [136]:
recession = np.array(df["YrSold"])

In [137]:
Y = unis=np.unique(recession).tolist()
Y = np.array(Y)
Y

array([2006, 2007, 2008, 2009, 2010])

In [138]:
X=np.array(df["SalePrice"])
X

array([208500, 181500, 223500, ..., 266500, 142125, 147500])

In [139]:
[list(recession).count(j) for j in unis]

[314, 329, 304, 338, 175]

I was trying to see if the housing market crash affected the sales of houses. 
I think this list shows that the recession did indeed affect the housing market.
See the previous 4 years with about 300 sales per year, and down to almost half that amount in the last